name: bicep-matrix
on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      matrix:
        description: "The second output string"
        value: ${{ jobs.create.outputs.matrix }}

jobs:
  create:
    name: matrix output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: matrix
        run: ./.github/workflows/scripts/bicep_matrix.sh
