name: verify-bicep
on:
  push:
    branches: [main]
    paths:
      - "**/*.bicep"
      - "**/*.bicepparam"
  pull_request:
    branches: [main]
    types: [opened, synchronize, edited, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  matrix-output:
    name: create matrix
    uses: ./.github/workflows/bicep_create_matrix.yml

  lint:
    needs: matrix-output
    strategy:
      matrix: ${{ fromJson(needs.matrix-output.outputs.matrix) }}
    name: ${{ matrix.name }}
    uses: ./.github/workflows/bicep_lint.yml
    with:
      bicepFilePath: "${{ matrix.path }}/${{ matrix.template }}"
