name: bicep - validate and deploy

on:
  push:
    branches: [main, develop]
    paths:
      - "**/*.bicep"
      - "**/*.bicepparam"
  pull_request:
    branches: [main, develop]
    paths:
      - "**/*.bicep"
      - "**/*.bicepparam"
      - ".github/workflows/bicep_test_and_deploy.yml"
      - ".github/workflows/bicep_verify.yml"
      - ".github/workflows/bicep_create_matrix.yml"
      - ".github/workflows/scripts/bicep_matrix.sh"
      - ".github/actions/bicep_lint/action.yml"
      - ".github/actions/bicep_validate/action.yml"
    types: [opened, synchronize, edited, ready_for_review]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  statuses: read

jobs:
  matrix-output:
    name: create matrix
    uses: ./.github/workflows/bicep_create_matrix.yml

  verify:
    if: github.event_name == 'pull_request'
    needs: matrix-output
    strategy:
      matrix: ${{ fromJson(needs.matrix-output.outputs.matrix) }}
    uses: ./.github/workflows/bicep_verify.yml
    name: ${{ matrix.name }}
    with:
      bicepFilePath: "./${{ matrix.path }}/${{ matrix.template }}"
      bicepParameters: "./${{ matrix.path }}/${{ matrix.parameters }}"
      runsOn: ubuntu-latest
      login: true
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  deploy:
    name: Deployment
    if: github.event_name == 'push'
    needs: matrix-output
    strategy:
      matrix: ${{ fromJson(needs.matrix-output.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - id: deploy
        name: deploy ${{ matrix.name }}
        uses: ./.github/actions/bicep_validate
        with:
          bicepFilePath: ./${{ matrix.path }}/${{ matrix.template }}
          bicepParameters: ./${{ matrix.path }}/${{ matrix.parameters }}
          deploymentScope: sub
          deploymentType: what-if # placeholder for now
          deploymentLocation: westeurope

  tag:
    name: 'set Tag "deployed"'
    needs: matrix-output
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-tags: true
          fetch-depth: 0
      - run: |
          git tag deployed origin/main --force
          git push origin --tags --force
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      # - name: set deployed tag
      #   uses: laputansoft/github-tag-action@v4.6
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     tag: 'deployed'
      #     release_branches: main
      #     default_bump: false
      #     create_annotated_tag: false
